removing sqlalchemy definitions and loading them via library hapi-schema
OCHA-DAP/hapi-pipelines pull request #28
Opened 2023-09-24 16:11 UTC by SimonbJohnson

The only problem I see is that hapi-schema package did not get added to the requirements.txt when I reran pip-compile.  I could add it manually, but assume this will be deleted when the command is re-run. 

Use
`pip install hapi-schema`
to install it

2023-09-24 20:33 UTC, mcarans requested changes
I think you need to add the hapi-schema library here:
https://github.com/OCHA-DAP/hapi-pipelines/blob/649a909ccae57f89591d5d62b09c3dabc26d13ca/pyproject.toml#L36-L41

Then pip-compile run automatically within the pre-commit hook will add it to the requirements.txt file.

2023-09-25 10:05 UTC, SimonbJohnson commented
That change has now been made

2023-09-25 10:09 UTC, turnerm approved these changes
Looks good to me pending my small comment and the changes that Mike requested

2023-09-25 10:09 UTC, turnerm commented on src/hapi/pipelines/app/__main__.py
> +        "project_configuration .yaml", main
typo?

2023-09-25 10:12 UTC, SimonbJohnson commented on src/hapi/pipelines/app/__main__.py
> +        "project_configuration .yaml", main
Yes, good spot, corrected!

2023-09-25 21:16 UTC, merged