Splitting config file to themes
OCHA-DAP/hapi-pipelines pull request #29
Opened 2023-09-26 12:56 UTC by SimonbJohnson

Leaving this in draft until the 3W config is ready to check it is working.

I pulled fields such as gender into a core as I wasn't sure if that would be used at some point across themes 

https://github.com/OCHA-DAP/hapi-pipelines/tree/splitting-config-file-to-themes/src/hapi/pipelines/configs

2023-09-28 11:35 UTC, turnerm reviewed
This looks really cool. I assume that ultimately we'd want to change the scraper to handle multiple configs - what do you think @mcarans @b-j-mills? But I think this is a great work-around in the meantime. 

Sorry in the meantime there's been a lot more population-related configuration added :sweat: But I think once you've pulled those in I would be fine with merging this.

@b-j-mills curious to know what you think!

2023-10-02 12:52 UTC, b-j-mills commented
Agreed!  It looks great - I'm happy for you to pull in the new pop/3W changes and merge.  I defer to @mcarans about expanding facade I believe to accommodate multiple configs.

2023-10-02 12:52 UTC, b-j-mills approved these changes

2023-10-02 13:10 UTC, SimonbJohnson commented
@b-j-mills @turnerm - I've merged main into this to solve conflicts. However when I run locally I get a keyerror as the HRPs have been removed from the config.

I also get this is in the current main branch.

Should I merge anyway?

```
raise KeyError(key)
    KeyError: 'HRPs'
```

2023-10-02 19:37 UTC, turnerm requested changes
@SimonbJohnson are you sure you were running the latest version? I got a couple of different errors but they're solved if you make the changes below

2023-10-02 19:37 UTC, turnerm commented on src/hapi/pipelines/configs/population.yaml
> -  headers: 2
I think these are missing

2023-10-02 19:37 UTC, turnerm commented on src/hapi/pipelines/configs/population.yaml
> +      - "#population+m+total"
These lines should be removed

2023-10-02 21:42 UTC, SimonbJohnson commented on src/hapi/pipelines/configs/population.yaml
> +      - "#population+m+total"
Updated to remove

2023-10-02 21:42 UTC, SimonbJohnson commented on src/hapi/pipelines/configs/population.yaml
> -  headers: 2
Updated to include

2023-10-02 21:42 UTC, SimonbJohnson commented
Yes, problem was I hand't updated after the merge. All working now!

2023-10-03 07:42 UTC, turnerm approved these changes

2023-10-03 07:45 UTC, turnerm commented
@SimonbJohnson can you just update the CHANGELOG? Then it should be good to merge!

2023-10-03 12:40 UTC, merged