Add OP fuzzy matching to utilities
OCHA-DAP/hapi-pipelines pull request #51
Opened 2023-10-13 15:38 UTC by b-j-mills

I created a utilities folder and added Mike's phonetics matching to use for the sectors and org types - I think this can develop as more countries are added and necessitate fuzzy matching.  The three countries we have now are so clean it's hard to really tell how deep we'll have to get into this.

2023-10-15 23:49 UTC, mcarans requested changes
Looks good so far. I think it would be helpful to add some tests with a few organisation type and sector variations to see how well the fuzzy matching might work.

2023-10-18 09:12 UTC, turnerm reviewed
Looks great! Just some small comments, and agree with Mike that it would be good to see it in action. If it's hard to add tests without real examples, should we just... add another country?

2023-10-18 09:12 UTC, turnerm commented on src/hapi/pipelines/utilities/text_parsing.py
> +    name: str, code_lookup: Dict[str, str], code_mapping: Dict[str, str]
Could you add a docstring that explains the parameters? (code_lookup and code_mapping can be confusing).

2023-10-27 16:47 UTC, b-j-mills commented
I'm pulling these changes into HAPI-252, so will close and create a new one for that branch!

2023-10-27 16:47 UTC, closed without merging